### PR TITLE
Fix attachments url in development js

### PR DESCRIPTION
**Pull request by id**

### CODE REVIEW

**Comment by id** [comment]
@clbn, please take a look. Tried to fix config for attachments but it still doesn't work on micropeppa.

**Comment by clbn** [comment]
@id It seems you are putting files into `pepyatka-html` instead of `pepyatka-server`.

**Comment by clbn** [comment]
@id Actually, that's fine, if you provide nginx some configuration to serve them after this.

**Comment by clbn** [comment]
@id But it also might be pretty confusing to put them there. Shall we put them on `m.micropeppa.freefeed.net` instead?

**Pull request merged**
